// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  events: dynamic(() => import("./Events")),
  team: dynamic(() => import("./Team")),
};
